### ISSUE TITLE
Issue with Zotero 6 + bootstrap plugin

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-plugin-template#105]
@northword @windingwind  我现在在用zotero6 bootstrap, 尝试开发插件, 但是使用模板build 的xpi插件不起作用, 我只改了package.json里面的name 和id, 下面是zotero 启动后打印出来的debug log, 请问下是什么原因导致的 
debug log(zotero 6):
```
[JavaScript Error: "expected expression, got '.'" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js" line: 5877 column: 31 source: "      return addon.data.locale?.stringBundle.GetStringFromName(localString);
"}]
startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js:99:3
```
我目前想要开发的功能是可以通过pdf的注释添加引用后, 直接链接跳转到另一个pdf的注释页面(引文的页面), 网上好像没有人做这个功能, 要不就不会这么伤脑筋了.

_Originally posted by @YaoLiMuMu in https://github.com/windingwind/zotero-plugin-template/issues/96#issuecomment-1986807672_

**Comment by windingwind** [comment]
@YaoLiMuMu
请勿在已关闭的无关问题下回复。

需要提供更多细节，例如，你测试的z版本，本仓库的分支，等等

**Comment by YaoLiMuMu** [comment]
对于我的不规范发言, 十分抱歉.
设备信息: Ubuntu 22.04.4 LTS
zotero version: zotero 6.0.35
repo分支: Zotero 6- bootstrap
分支版本为最新版, commit号码: 9850e5e67633a808eed138e651d4266bc304a45f
补充信息: 我尝试了直接用默认配置, 无修改package.json, 构建后的插件xpi也是可以导入, 但是无法生效(比如 make it red等)

**Comment by volatile-static** [comment]
这个想法很不错，但为什么要在Z6实现呢

**Comment by YaoLiMuMu** [comment]
> 这个想法很不错，但为什么要在Z6实现呢

因为我目前在用客户端版本是zotero6, 算是自动升级的正式版, 之所以没有主动升级, 
一是因为有个好用的预览插件quicklook ((https://github.com/mronkko/ZoteroQuickLook))已经没人维护到zotero7, 虽然我尝试接力, 但是这个项目代码比较混乱, 我也不熟悉js语言和网页技术, 只修改了一部分勉强使用.
二是目前我本地文件云同步还有些问题没解决, 但是升级后解决不了.

**Comment by YaoLiMuMu** [comment]
@volatile-static 贡献者大哥, 你看看我上面debug log, 能发现是什么问题吗?

**Comment by windingwind** [comment]
从用户角度是推荐使用稳定版本的，从插件开发角度需要考虑到整个平台未来的发展方向。z6即将停止支持且z7相比6有很大的变化，包括部分插件功能的替代（例如，你提到的quicklook可由内置的侧边栏预览替代）。现在开始做插件，不推荐还按照z6来设计功能与开发。

看起来你使用本仓库没有明显的问题，可关注`bootstrap.js:99:3`是什么。在这一行报错停止加载插件

**Comment by northword** [comment]
[JavaScript Error: "expected expression, got '.'" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js" line: 5877 column: 31 source: " return addon.data.locale?.stringBundle.GetStringFromName(localString); "}]

这个看起来更像是这个地方语法错误了，需要看看index.js第5587行附近，以及这一行对应的构建前源码

**Comment by YaoLiMuMu** [comment]
> [JavaScript Error: "expected expression, got '.'" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/[nebula1703@nebula.com.xpi](mailto:nebula1703@nebula.com.xpi)!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/[nebula1703@nebula.com.xpi](mailto:nebula1703@nebula.com.xpi)!/chrome/content/scripts/index.js" line: 5877 column: 31 source: " return addon.data.locale?.stringBundle.GetStringFromName(localString); "}]
> 
> 这个看起来更像是这个地方语法错误了，需要看看index.js第5587行附近，以及这一行对应的构建前源码

这个index.js是自动生成的, 怎么找它的构建前码源, 我在下面打印的是build自动构建出来的index.js 在第5587附近的代码, 好像难以发现问题:
```javascript
5875   function getString(localString, noReload = false) {
5876     try {
5877       return addon.data.locale?.stringBundle.GetStringFromName(localString);
5878     } catch (e) {
5879       if (!noReload) {
5880         initLocale();
5881         return getString(localString, true);
5882       }
5883       return localString;
5884     }
5885   }
```

**Comment by volatile-static** [comment]
因为插件模板是基于Z7的，ts编译的目标是ff102，导致`?.`语法没有转换为Z6（ff60）支持的js代码。

**Comment by windingwind** [comment]
可尝试在`scripts/build.mjs` L111 加入一行`target: "firefox60",`

**Comment by YaoLiMuMu** [comment]
hello , 我尝试加入target, 但是好像不起作用 `vim scripts/build.mjs`
```javascript
104   await build({
105     entryPoints: ["src/index.ts"],
106     define: {
107       __env__: `"${env.NODE_ENV}"`,
108     },
109     bundle: true,
110     outfile: join(buildDir, "addon/chrome/content/scripts/index.js"),
111           target: "firefox60",
112     // Don't turn minify on
113     // minify: true,
114   }).catch(() => exit(1));
```
不过zotero debug log 与之前不一样了
```log
[JavaScript Error: "Zotero.Plugins is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js" line: 584}]
_ensurePluginListener@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js:584:11
addListenerCallback@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js:496:13
_ensureAutoUnregisterAll@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js:604:11
node_modules/zotero-plugin-toolkit/dist/managers/keyboard.js/KeyboardManager<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js:1667:11
node_modules/zotero-plugin-toolkit/dist/index.js/ZoteroToolkit2<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js:5824:27
Addon<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js:7052:19
@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js:7068:25
@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js:2:1
startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js:99:3
```

**Comment by windingwind** [comment]
执行`npm i zotero-plugin-toolkit@2.1.3`，然后重新编译

**Comment by northword** [comment]
显然添加target后是有效的，报错信息已经变成Zotero.Plugins未定义，这可能是你代码的问题而不是模板的问题了。

**Comment by YaoLiMuMu** [comment]
@windingwind @northword 感谢你们的帮助, 就是要执行`npm i zotero-plugin-toolkit@2.1.3`后, 插件就可以用了, 可是这包我看到在package.json 里面默认就添加进去了,
```javascript
 43   "dependencies": {
 44     "zotero-plugin-toolkit": "^2.1.3"
 45   },
```

**Comment by windingwind** [comment]
> 感谢你们的帮助, 就是要执行npm i zotero-plugin-toolkit@2.1.3后, 插件就可以用了, 可是这包我看到在package.json 里面默认就添加进去了,

`npm i`对于`"^2.1.3"`依赖版本，默认下载`2.1.3`-`3.0.0`之间的最新版本。从近几个版本开始，toolkit未在z6上测试，实质上已经停止对z6支持，因此无法运行。

> 另外请问下这个模板好像不支持在reader中添加 右击批注项目(批注好像也是item)的方式, 比如下图, 我想在选中的批注菜单栏中添加一项

需要z7提供的官方api:

https://github.com/windingwind/zotero-types/blob/1767c450bc38b9c23eea0e18aac677d820efa5d9/types/xpcom/reader.d.ts#L303-L342

**Comment by YaoLiMuMu** [comment]
> > 感谢你们的帮助, 就是要执行npm i zotero-plugin-toolkit@2.1.3后, 插件就可以用了, 可是这包我看到在package.json 里面默认就添加进去了,
> 
> `npm i`对于`"^2.1.3"`依赖版本，默认下载`2.1.3`-`3.0.0`之间的最新版本。从近几个版本开始，toolkit未在z6上测试，实质上已经停止对z6支持，因此无法运行。
> 
> > 另外请问下这个模板好像不支持在reader中添加 右击批注项目(批注好像也是item)的方式, 比如下图, 我想在选中的批注菜单栏中添加一项
> 
> 需要z7提供的官方api:
> 
> https://github.com/windingwind/zotero-types/blob/1767c450bc38b9c23eea0e18aac677d820efa5d9/types/xpcom/reader.d.ts#L303-L342

好伤心, zotero 6 不支持reader的批注菜单添加吗?看看只能勉强绑定快捷键使用了

**Comment by windingwind** [comment]
是的，很遗憾。所以建议插件以z7为基础开发

**Comment by YaoLiMuMu** [comment]
那请问下zotero 6 支持获得当前被选中的批注的元信息(metadata)吗? 我只找到了半天只看到页面的全局获取. 心情郁闷

**Comment by volatile-static** [comment]
z6没几天活头了，真别搞了

**Comment by YaoLiMuMu** [comment]
好像被劝服了, zotero 7 大约什么时候正式上线.

**Comment by volatile-static** [comment]
有点地狱笑话了，z7稳定版预计于去年正式发布

**Comment by YaoLiMuMu** [comment]
@windingwind @northword
因为不是JS和网页开发者, 我提出的问题比较多, 如有打扰, 着实抱歉.  
按照你的建议, 已经升级到zotero 7了, 现在直接用你的action&tags插件配合脚本来实现批注的超链接功能
我目前遇到一个难题, 我已经获取的目标批注的元信息了, 包括"key", "parentitem", "annotationPageLaber"...这些, 那如何打开目标PDF并且跳转到对应批注的页面位置, 我找不到相关的接口和函数, 请问笔记窗口上面的"Show On Page"功能能对外使用吗?
![image](https://github.com/windingwind/zotero-plugin-template/assets/32826811/e0df1cf5-aa00-4dbe-8993-07b072395b48)

**Comment by northword** [comment]
我对 reader /批注 相关的接口不熟悉，你可以参考 zotero-types 看看有没有接口。

**Comment by windingwind** [comment]
https://github.com/zotero/zotero/blob/f8d59d14bc2f7c3a9a8ccd6ac41b01fe209aa5da/chrome/content/zotero/xpcom/fileHandlers.js#L494-L499

**Comment by YaoLiMuMu** [comment]
> https://github.com/zotero/zotero/blob/f8d59d14bc2f7c3a9a8ccd6ac41b01fe209aa5da/chrome/content/zotero/xpcom/fileHandlers.js#L494-L499

感谢你指导, 可是我尝试一下, 好像提示操作失效, 在测试代码如下:
```javascript
let test = ZoteroPane.getSelectedItems()[0].getAttachments();
var atta = Zotero.Items.get(test);
Zotero.FileHandlers.open(atta, {
			location: {
				"annotationID": "5GEJUHNM",
				"pageIndex": "9",
			    }});
```
主要log 信息如下:
```log
[JavaScript Error: "TypeError: item.getFilePathAsync is not a function" {file: "chrome://zotero/content/xpcom/fileHandlers.js" line: 32}]

[JavaScript Error: "TypeError: item.getFilePathAsync is not a function" {file: "chrome://zotero/content/xpcom/fileHandlers.js" line: 32}]
```
码源位置
```javascript
	async open(item, params) {
		let { location, openInWindow = false } = params || {};
		
		let path = await item.getFilePathAsync();
		if (!path) {
			Zotero.warn(`File not found: ${item.attachmentPath}`);
			return false;
		}
```

**Comment by volatile-static** [comment]
你单步调试看一下变量类型就知道了

**Comment by YaoLiMuMu** [comment]
抱歉, 是我粗心大意了, 确实没有注意到这是个数组.
@windingwind , 太感谢你的解答, 
最后问个问题应该就大功告成了, 就是我已知一个附件pdf的key, 如何获取到它的itemID? 我需要用到通过Zotero.Items.get(itemID)获得item作为Zotero.FileHandlers.open的输入.

**Comment by windingwind** [comment]
`Zotero.Items.getByLibraryAndKey`

通过libraryID和itemKey获取Zotero.Item实例。

**Comment by volatile-static** [comment]
像这种很基本的功能建议直接翻types仓库，甚至GPT可能都知道

**Comment by YaoLiMuMu** [comment]
@windingwind @volatile-static 算是实现了, 分享内容链接: https://github.com/windingwind/zotero-actions-tags/discussions/296

**Comment by volatile-static** [comment]
很棒！顺便提醒一点， @northword 也对此有不少帮助的
