### ISSUE TITLE
'keyOptions.keyboard' is possibly 'undefined'.

### ISSUE THREAD

**Issue by carljoseph** [windingwind/zotero-plugin-template#110]
Trying to set up a basic new plugin by following the instructions. When I do a `npm run build`, I get the following error:

`'keyOptions.keyboard' is possibly 'undefined'.`

Any ideas? Am not too familiar with JS/TS development.

**Comment by northword** [comment]
https://github.com/windingwind/zotero-plugin-template/pull/109/commits/863f5a0fafc4b81dcdb07d5c2d93f29b55fa6f0c

it's a bug, do this to fix it, then build again.

**Comment by carljoseph** [comment]
Perfect. Thank-you.
