### ISSUE TITLE
zotero not able to find the boostrap methods

### ISSUE THREAD

**Issue by carljoseph** [windingwind/zotero-plugin-template#111]
Still having some problems getting the examples running. When I enable/disable the plugin in Zotero, the console says that it can't find the bootstrap methods for startup & shutdown. No doubt I've done something wrong here in [my repo](https://github.com/carljoseph/zotero-reporter)?

<img width="975" alt="Screenshot 2024-04-01 at 16 42 36" src="https://github.com/windingwind/zotero-plugin-template/assets/4588120/e91e004d-54d1-462d-9ccf-7f7af3f1f2cc">

Thx.

**Comment by northword** [comment]
package.json

```diff
  "config": {
    "addonName": "Zotero Reporter",
    "addonID": "zotero-reporter@carljoseph.com.au",
    "addonRef": "zotero-reporter",
--  "addonInstance": "Zotero.${addonInstance}",
--  "prefsPrefix": "extensions.zotero.${addonRef}",
++  "addonInstance": "Reporter",
++  "prefsPrefix": "extensions.zotero.reporter",
    "releasePage": "https://github.com/carljoseph/zotero-reporter/releases",
    "updateJSON": "https://raw.githubusercontent.com/carljoseph/zotero-reporter/main/update.json"
  },
```

**Comment by windingwind** [comment]
https://github.com/carljoseph/zotero-reporter/blob/7dfc936a63c4f64f8d4bf202aaf5d2964285b3f7/package.json#L9-L10

The `addonInstance` should be a valid JS variable name and `addonRef` should be valid CSS and Fluent string

**Comment by windingwind** [comment]
```diff
++  "addonInstance": "Reporter",
```

Emm... `Zotero.Reporter` might not be a good definition for me. Maybe `ReporterPlugin` or something that's less likely to cause conflict?

**Comment by windingwind** [comment]
BTW, the plugin name `Zotero Reporter` is not a very good idea, since `Zotero` is a registered trademark and the team suggests plugin developers not to use a name like `Zotero XYZ`, instead use `XYZ for Zotero`, to not mislead users that it's an official Zotero software. (The GitHub repo name can be an exception since it's not for users)

**Comment by northword** [comment]
> Emm... Zotero.Reporter might not be a good definition for me. Maybe ReporterPlugin or something that's less likely to cause conflict?

Indeed, I was just trying to express that it's here that there is a issue, and ignoring this word easily leads to confusion.

**Comment by carljoseph** [comment]
Thanks for your patience and help folks. Have changed the naming of the plugin, etc. but I'm still getting the same console error.

I'm new to this, and basically trying to get the plugin template examples working to get me started. Thx

**Comment by northword** [comment]
Already restarted Zotero and dev servers? (kill zotero and re-run `npm start`)

**Comment by carljoseph** [comment]
Yep, indeed. Here's what it looks like (with Zotero not started at the beginning) ... 

https://github.com/windingwind/zotero-plugin-template/assets/4588120/5aa71a52-64bf-4e07-b903-bf323fe09a8c

**Comment by northword** [comment]
![image](https://github.com/windingwind/zotero-plugin-template/assets/44738481/ed0d4dc9-7241-431d-a556-8e09a5952fdc)

but it's running for me.

use a beta version zotero? 

let me see your `build/addon/bootstrap.js` ?

**Comment by carljoseph** [comment]
`bootstrap.js` is unchanged - https://github.com/carljoseph/zotero-reporter/blob/main/addon/bootstrap.js

All I changed was the `config` in the `package.json`

**Comment by northword** [comment]
I guess, please quit Zotero completely, mac systems need to be quit manually by right clicking on the tray icon, not just closing the main window.

**Comment by carljoseph** [comment]
Definitely quit. No presence of it in activity monitor either either.

**Comment by northword** [comment]
try restart pc (An attempt that seems silly but works most of the time.

**Comment by carljoseph** [comment]
Unfortunately no change :( 

Just reverted back to the start. When I download the plugin template code, update the `zotero-cmd.json`, do the whole `npm install`, `npm run build`, `npm start` and I get the same error in Zotero.

However, if I install the .xpi plugin itself after building it, it works fine ¯\_(ツ)_/¯

**Comment by windingwind** [comment]
Please check the plugin directory if it's an `xpi` or the text file linking to the dev build. I guess if you manually installed a plugin from xpi, the `npm run start` will not be able to overwrite it to the dev build.

**Comment by carljoseph** [comment]
Thanks for the idea. I set up a completely new profile in Zotero and still get the same problem :(

**Comment by carljoseph** [comment]
> Enable the plugin if it was disabled, then quit Zotero and run `npm start` again.

Now why did that do the trick?! Thank you!! 

So here's the full process to get it to work ...
1. Create a new Zotero profile `zotero -p`
2. Manually create the `extensions` folder in your profile directory '/Users/user.name/Library/Application Support/Zotero/Profiles/1e736rli.dev2/extensions/` (for some reason `npm start` fails if it doesn't already exist)
3. Update `zotero-cmd.json` 
4. `npm start`
5. Enable the plugin
6. Shut down Zotero
7. `npm start` again

Thank you everyone for your patience and help with this.

**Comment by windingwind** [comment]
Should be fixed in the latest plugin template.
