### ISSUE TITLE
Suggestion for developing new addons from templete

### ISSUE THREAD

**Issue by brunoalbertopeixoto** [windingwind/zotero-plugin-template#115]
I imagine it's difficult to program. But here's a suggestion: you could re-edit this code to make the addons functional again in the recent version of Vertov (eg audio and video media files/https://web.archive.org/web/20130602162235/http://digitalhistory. concordia.ca/vertov/?page_id=6) and develop something to read texts by voice (https://github.com/ImperialSquid/zotero-zotts).

**Comment by windingwind** [comment]
Please report to https://forums.zotero.org/discussions

**Comment by ImperialSquid** [comment]
@brunoalbertopeixoto 

Just a little note to say I'll be picking up development on that TTS plugin soon, I started it last year but had to semi-abandon it due to a whole bunch of personal issues coming up, now I'm more able to work on it I'm hoping to return to the project soon!
