### ISSUE TITLE
Compatibility with Zot6 and Zot7

### ISSUE THREAD

**Issue by denismaier** [windingwind/zotero-plugin-template#124]
Is this template currently compatible with both Zotero 6 and 7? If yes, do you have to do anything special for this?

**Comment by windingwind** [comment]
Branches with names starting with zotero6 or zotero7 are compatible to the corresponding app version, while the main branch only promises compatibility with the latest beta/dev version of Zotero.

**Comment by windingwind** [comment]
We don’t recommend developing plugins for Zotero 6 at this point (see other discussions in this repo)

**Comment by denismaier** [comment]
Ok. Thanks.
