### ISSUE TITLE
Need Examples of VirtualizedTable on Dialog 【需要对话框中插入表格的示例】

### ISSUE THREAD

**Issue by StevenGLee** [windingwind/zotero-plugin-template#160]
> Background: I'm new to JavaScript/TypeScript and zotero plugin development is my first attempt to use JavaScript/TypeScript. Also, I'm not familiar with Zotero's API.

There's not yet an example that creates a VirtualizedTable in a Dialog according to the fragment brlow:

``` javascript
// src/modules/examples.ts
@example
static vtableExample() {
  ztoolkit.getGlobal("alert")("See src/modules/preferenceScript.ts");
}
```

I tried to creates a VirtualizedTable in a Dialog like below:
```javascript
const renderLock = ztoolkit.getGlobal("Zotero").Promise.defer();
const dialogHelper = new ztoolkit.Dialog(10, 2);
dialogHelper.open("Dialog Example");
const tableHelper = new ztoolkit.VirtualizedTable(dialogHelper.window)
```
but it doesn't work. I don't know how to fix it.

For beginners, the `vtableExample` is rather necessary.

**Comment by northword** [comment]
https://github.com/windingwind/zotero-better-notes/blob/master/src%2Fmodules%2Fsync%2FmanagerWindow.ts

https://github.com/syt2/zotero-addons/blob/main/src%2Fmodules%2FaddonTable.ts#L136

**Comment by StevenGLee** [comment]
> https://github.com/windingwind/zotero-better-notes/blob/master/src%2Fmodules%2Fsync%2FmanagerWindow.ts
> 
> https://github.com/syt2/zotero-addons/blob/main/src%2Fmodules%2FaddonTable.ts#L136

Thanks a lot!

**Comment by windingwind** [comment]
The `ztoolkit.Dialog` is meant for creating straightforward dialog windows with form elements such as checkboxes and inputs, without the need for complex xhtml files, script/style loading, and data binding.

The v-table is not suitable for these scenarios. When dealing with windows requiring complex logic, it's always better to design an actual window with proper xhtml, CSS, JavaScript, etc.
