### ISSUE TITLE
TagRaw problem on windows 

### ISSUE THREAD

**Issue by lisboarocha** [windingwind/zotero-plugin-template#172]
Hello,

When executing templates, I'm getting this:

> [JavaScript Error: "TypeError: tagRaw is null" {file: "jar:file:///C:/Users/F%C3%A1bio/AppData/Roaming/Zotero/Zotero/Profiles/4zp4l8ei.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/BetterNotes.js line 56012 > AsyncFunction" line: 7}]

Info about the system:

> appName => Zotero, version => 7.0.3 (x64), os => Windows 11 22631, locale => pt-BR, extensions => Better Notes for Zotero (2.0.3, extension)

Do you have any idea about that?

Thanks for this great job!

**Comment by northword** [comment]
This seems to be a BetterNotes bug rather than a bug in this template?

**Comment by lisboarocha** [comment]
oh, sorry! Absolutely!
