### ISSUE TITLE
Can I register a new function to the toolbar? 

### ISSUE THREAD

**Issue by brick-pid** [windingwind/zotero-plugin-template#173]
I am trying to develop a new plugin designed to randomly open a file when clicked. Currently, this plugin can be activated through a menu item, but this requires first clicking on the menu and then on the corresponding feature, which is rather cumbersome. I referred to the [UI Examples](https://github.com/windingwind/zotero-plugin-template/tree/main?tab=readme-ov-file#ui-examples), but it seems they do not mention any relevant information.

The target behavior is as shown in the following diagram, when this button is clicked, the related function will be activated.

![CleanShot 2024-08-31 at 15 46 51](https://github.com/user-attachments/assets/100a0adf-6290-467c-86a7-eec802d0dfee)

**Comment by northword** [comment]
https://github.com/syt2/zotero-addons/blob/a9647a586cf104c353b99ab82727b52c16d576ac/src/modules/addonTable.ts#L71

**Comment by windingwind** [comment]
Generally I don’t recommend adding new buttons to the library toolbar, as most of the plugins’ icons are not well designed and can be distracting, unless the entry is very frequently used and highly related to the items in library.

**Comment by brick-pid** [comment]
> Generally I don’t recommend adding new buttons to the library toolbar, as most of the plugins’ icons are not well designed and can be distracting, unless the entry is very frequently used and highly related to the items in library.

Thanks for your answer. I think your answer makes sense. I've now bound it to a shortcut key, which I think might be better.
