### ISSUE TITLE
The build doesn't use typescript type-checking

### ISSUE THREAD

**Issue by retorquere** [windingwind/zotero-plugin-template#22]
`esbuild` doesn't do anything with typescript except strip it down to javascript while bundling. To get the benefits of typescript, we'd need to run `tsc --noEmit` and/or `eslint` in parallel with build.js. To do this in a cross-platform way would require the use of `worker_threads`. For linux/macos it'd be easy to do using GNU `parallel`, but on windows this requires installing `git-bash` (which may be a reasonable ask, I don't use windows though).

**Comment by windingwind** [comment]
Thanks for the suggestion! Code check (`tsc` or `eslint`) is definitely a must.

Should the build step be aborted if `tsc` fails with errors, or just log the errors and continue?

**Comment by retorquere** [comment]
I can't speak for the general case, but for me a tsc failure is a build failure.

**Comment by volatile-static** [comment]
Sometimes it would be annoying when debug some experimental code, I guess. Maybe we can let it make a confirm to us either continue or abort?

**Comment by retorquere** [comment]
I cant speak for the general case. My personal view is "there's nothing quite as permanent as a temporary solution", so my debug code needs to pass too. You can always add TS-ignore.

**Comment by volatile-static** [comment]
> there's nothing quite as permanent as a temporary solution
Make sense.
