### ISSUE TITLE
Table disappears when open preference window the second time

### ISSUE THREAD

**Issue by lzhmarkk** [windingwind/zotero-plugin-template#28]
I built the latest version locally and import the demo plugin into my Zotero, it seems work well. When I open the preference window, I could see the preference table perfectly. However, after closing the preference window and reopen i, I found that the preference table disappear, no matter how many times I reopen the window.

This is what I saw when open the window for the first time:

<img width="731" alt="截屏2023-03-12 22 05 49" src="https://user-images.githubusercontent.com/42379096/224550215-d85631a1-c413-4553-9095-93afdb9665be.png">

When I open the preference window for the second time, the table disappears:

<img width="717" alt="截屏2023-03-12 22 05 58" src="https://user-images.githubusercontent.com/42379096/224550207-b5ec7b27-737f-48c8-bba0-7afee8fe76a9.png">

**Comment by windingwind** [comment]
fixed
