### ISSUE TITLE
multiline editable custom field 

### ISSUE THREAD

**Issue by themetalleg** [windingwind/zotero-plugin-template#35]
Hi, is it possible to register an editable custom field with mutiple lines (allowing line breaks)?
Thanks for your help in advance.

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-pdf-translate/blob/main/src/modules/itemBox.ts

**Comment by windingwind** [comment]
I'll look into it later... Please forgive me for the late reply as I'll be travelling for the next whole week.

**Comment by windingwind** [comment]
Seem like Zotero force unfocused the input element when pressing `enter`, which makes it not possible for users to type a line break.

One possible workaround is to open a dialog with an input when focusing the input element of that extra field. The toolkit provides a helper class `Dialog` for creating dialog window without writing a `html` file easily and with variables binding. We handle user input with line breaks in that dialog and replace them with `<br>` before saving back to the extra field.
