### ISSUE TITLE
Plugins error if using node built-ins

### ISSUE THREAD

**Issue by ImperialSquid** [windingwind/zotero-plugin-template#39]
I'm trying to make a plugin, but it relies on spawning a child process to manage some stuff on the command line. The building process seems to work fine, but it seems like Zotero can't handle some modules

This test code:

![test_ts](https://user-images.githubusercontent.com/44560551/235583007-85052ba4-90c4-4868-a99a-997c61a3f02d.PNG)

Results in this error:

![error](https://user-images.githubusercontent.com/44560551/235583048-853fa66a-f5f4-4a8f-879e-646ae7871555.PNG)

Due to this line in the built code:

![test_js](https://user-images.githubusercontent.com/44560551/235583092-f4a207a6-5336-4d4a-a69e-73e076aa99eb.PNG)

I think it's an issue with modules built in to node, but I'm not sure if that's the issue, and I'm also unsure how to solve this (JS isn't my area of expertise so apologies if any of this is incorrect/obvious to fix!)

**Comment by windingwind** [comment]
Oh yes, Zotero runs in a pure browser environment, thus the node things are not available.

The compiler (esbuild) will not bundle built-in modules, leaving a `require(xxx)` in the output `index.js`. However, as the error log says, `require` is not defined in Zotero's browser env. You may find another `require` function in the Zotero's main window environment, which is designed to import some Zotero's modules, totally different from the native `require`.

To execute a command line, use:

```js
await Zotero.Utilities.Internal.exec('/path/to/exe', ['-arg1', 'arg2', ...]);
```

This is a wrapper of the Mozilla's process module. See the Mozilla doc for more details: http://www.devdoc.net/web/developer.mozilla.org/en-US/docs/XPCOM_Interface_Reference/nsIProcess.html

**Comment by ImperialSquid** [comment]
Thanks for the quick reply!

Running in a browser like environment seems very strange but thanks for finding an alternative!

One problem though, part of my plugin is going to require reading back from the command line upon completion, it looks like the wrapper within Zotero just returns true if it succeeds and there's no way to pass in a callback or anything...

Would you recommend working with the nsIProcess thing directly or is there some other clever work around I could use?
