### ISSUE TITLE
Plugin built from source is not compatible with zotero7beta

### ISSUE THREAD

**Issue by Zz-dong** [windingwind/zotero-plugin-template#43]
Hi, I'm following the instructions in “Build From Source”. But the plugin is not compatible with Zotero.
```
npm run build-dev

> zotero-addon-template@0.1.6 build-dev
> cross-env NODE_ENV=development node scripts/build.mjs

(node:3656) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future 
version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3656) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[Build] BUILD_DIR=builds, VERSION=0.1.6, BUILD_TIME=2023-06-09 22:41:30, ENV=development
[Build] Run esbuild OK
[Build] Run replace in  [ 'update.json : 5 / 5', 'update.rdf : 4 / 4' ]
[Build] Replace OK
[Build] Addon prepare OK
[Build] Addon pack OK
[Build] Finished in 0.35 s.
```
![image](https://github.com/windingwind/zotero-plugin-template/assets/78004570/fd7211ca-f6fe-4da2-af9b-dbc87bae30eb)
I used the xpi released in the repository. It worked
![image](https://github.com/windingwind/zotero-plugin-template/assets/78004570/0ea3b479-54fa-413a-a5f4-3de5269f864a)
I'm not sure if I did something wrong. By the way, the Chinese document needs to be updated.

---

# system information
windows 10 x64 - VMware Workstation
Node.js v18.16.0
Zotero 7.0.0-beta.9+5e41b3ab4 (64-bit)

**Comment by northword** [comment]
上游 bug 导致，将依赖项 replace-in-file 降级到 6.3.5。
关注 https://github.com/adamreisnz/replace-in-file/issues/165

**Comment by Zz-dong** [comment]
@northword thanks.
