### ISSUE TITLE
[Announcement] Auto Hot Reload

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-plugin-template#44]
Hi there,

I’m happy to tell you that the plugin hot reload (update code and resources without restarting Zotero) feature is done. I have added the `Auto Hot Reload` feature to the plugin template and invite you to take a look and have a try.

1. Run `npm run start-watch`. (If Zotero is already running, use `npm run watch`)
2. Coding. (Yes, that's all)

When file changes are detected in `src` or `addon`, the plugin will be automatically compiled and reloaded.

**Comment by lifan0127** [comment]
Thanks! How to leverage this feature from an existing project?

**Comment by northword** [comment]
> Thanks! How to leverage this feature from an existing project?

@lifan0127 see readme:

![Screenshot_2023-07-02-08-55-45-117_org.mozilla.firefox.jpg](https://github.com/windingwind/zotero-plugin-template/assets/44738481/9d488613-4a9f-45c6-a381-ae6cb4bbefe1)

**Comment by lifan0127** [comment]
@northword Thank you! 

It works great! Really appreciate all your effort to make such a useful tool @windingwind !
