### ISSUE TITLE
How to access Zotero Items in a hierarchical manner?

### ISSUE THREAD

**Issue by ShreyJ1729** [windingwind/zotero-plugin-template#52]
I'm building a private cloud for my zotero, and was wondering how to access the files in a hierarchical way?
E.x. looking at the following image, I'd like to have some sort of indication that the attachment "reddit post snapshot" is a child of the item "an incredible workflow".

To my knowledge Zotero.Items currently just gives a flattened list of items.

<img width="934" alt="image" src="https://github.com/windingwind/zotero-plugin-template/assets/23284483/5c0153a0-1e3d-4a5b-a429-7b5e98a61a3e">

**Comment by windingwind** [comment]
1. First get the parent item (an incredible...). Generally, we use `const item = Zotero.Items.get(id)`
2. Then use `const attachments = item.getAttachments()`. `attachments` is an array of ids of the attachment items ([ID_OF_REDDIT_SNAPSHOT,]).
3. Get the snapshot item by id. `const snapShotItem = Zotero.Items.get(attachments)[0]`. If there are multiple attachments, you may want to filter by attachment type.
