### ISSUE TITLE
Use react for plugin development

### ISSUE THREAD

**Issue by lifan0127** [windingwind/zotero-plugin-template#56]
Hi, I have seen some Zotero plugins built with React: https://github.com/diegodlh/zotero-cita

Is it supported by zotero-plugin-template? Thanks!

**Comment by windingwind** [comment]
Yes. To get the react instance: `const React = ztoolkit.getGlobal("require")("react")` (or, `Zotero.getMainWindow().require("react")`)

**Comment by lifan0127** [comment]
Thanks, @windingwind  Is there a zotero-plugin-template based plugin implemented in React that I can use as a guide?

**Comment by windingwind** [comment]
React is a framework to create UI components. If you are not doing a lot of reusable UI stuff, no need to use it.

**Comment by lifan0127** [comment]
Thanks for the guidance!
