### ISSUE TITLE
Errors after I install the template xpi

### ISSUE THREAD

**Issue by pjnkun** [windingwind/zotero-plugin-template#70]
Hello Windingwind, 

I'm new to build the plugins and I found your significant contribution in this area and thanks for providing such a comprehensive guide, but I just came into some problems here. 
I'm using Apple Silicon Zotero 7 the latest build to test the plugin template for the first time. After I successfully compiled, I was installing the xpi file via the GUI of Zotero 7. However, the Zotero Addon Template is showing the Addon is loading to 30% and stopped moving. 
Then I opened the error console, it shows that

- Uncaught (in promise) undefined 2
- TypeError: this.globalCache is undefined [addontemplate.js:1597:15]
- TypeError: this.gViewSourceUtils is undefined5 [webconsole.js:225:5](resource://devtools/client/webconsole/webconsole.js)
    viewSource resource://devtools/client/webconsole/webconsole.js:225
    onViewSource resource://devtools/client/webconsole/service-container.js:43
    onClick resource://devtools/client/shared/components/Frame.js:259
    React 19
    dispatchInteractiveEvent self-hosted:1162

Would you have any idea what's the root cause and how to fix it? 

Thanks
pjnkun

**Comment by windingwind** [comment]
Zotero 7 beta is not a stable release and we cannot follow up all changes immediately.

The `registerCustomCellRenderer` is removed because the `ztoolkit.ItemTreeManager.addRenderCellHook` is deprecated. The latest source code should create a valid build.

Please pull and run `npm install` once to update dependencies.
