### ISSUE TITLE
oncommand vs commandListener

### ISSUE THREAD

**Issue by denismaier** [windingwind/zotero-plugin-template#73]
Hi, I'm trying to understand how this template works. My TS/JS knowledge is limited so it's not so easy for me.

What is the difference between `oncommand`, and `commandListener`? Are there recommendations which one should be used?

E.g., I have this:

```typescript
export class TestUI{

  static registerRightClickMenuPopup() {
    ztoolkit.Menu.register(
      "item",
      {
        tag: "menu",
        label: getString("menupopup-label"),
        children: [
          {
            tag: "menuitem",
            label: getString("menuitem-test1"),
            oncommand: "alert('asdf')",
          },
          {
            tag: "menuitem",
            label: getString("menuitem-test2"),
            commandListener: () => test(),
          },
          {
            tag: "menuitem",
            label: getString("menuitem-test3"),
            oncommand: "test()",
          },
        ],
      },
      "before",
      document.querySelector(
        "#zotero-itemmenu-addontemplate-test",
      ) as XUL.MenuItem,
    );
  }

function test() {
  //alert('Hi'); //alert does not seem to be in scope here...
  ztoolkit.getGlobal("alert")("Hi");
}
```

Calling the function `test` with `commandListener` works, but not with `oncommand`. Also, `alert` works when used directly on `oncommand`, but not inside a function. Why is that?

**Comment by windingwind** [comment]
For elements, each event will trigger the corresponding `addEventListener` and `on...` (e.g. `onclick`) attributes. See https://stackoverflow.com/questions/6348494/addeventlistener-vs-onclick

`command` is an event type for some XUL elements. So here the `oncommand` is a string that will be executed in the `window` scope, while the `commandListener` adds an event listener for event type `command`.

> Calling the function test with commandListener works,

The arrow function you use here inherited the scope of this code, which is the plugin sandbox. So it calls the `test` defined here.

> but not with oncommand.

Right. The `oncommand` is evaluated in the window scope, where the `test` does not exists. You may also see error log in the console.

> Also, alert works when used directly on oncommand,

Right. `alert` is a window-dependent function, which exists in window scope.

> but not inside a function. Why is that?

The plugin sandbox is a non-window scope, similar to a web worker. `alert` is not part of it.

**Comment by windingwind** [comment]
> Are there recommendations which one should be used?

Depends on your need. Generally, we recommend `commandListener ` (which is `addEvenListener`) to make the full use of TS hints.

**Comment by denismaier** [comment]
Ok. Thanks. I'll go with that.
