### ISSUE TITLE
meaning of @example?

### ISSUE THREAD

**Issue by denismaier** [windingwind/zotero-plugin-template#76]
What's the exact meaning and purpose of `@example` in the template? (A guess: it's probably somehow possible to keep the examples for reference, but suppress them when building. Is that correct? If so, how would that work?)

**Comment by windingwind** [comment]
Comment out this line and all functions with the `@example` decoration will not be actually executed: https://github.com/windingwind/zotero-plugin-template/blob/77e43bf3782931c5aa5cf7e441564bac009dffe2/src/modules/examples.ts#L13

This is also for having more detailed logs by logging when an example is triggered. People who are not familiar with Zotero can sometimes be confused by how the hooks and lifecycle works.

**Comment by northword** [comment]
It's a decorator: https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by denismaier** [comment]
Ok. Thanks. That makes it clearer.

> Comment out this line and all functions with the @example decoration will not be actually executed: 

Would it make sense to add this somewhere as a global build option? Or is that actually not necessary since the built plugin will only contain code that is actually used? IIUC, if I don't call the examples via hooks, they will not be included when building the release version.

**Comment by windingwind** [comment]
Technically, if the entrance `index.ts` does not use a file, then it will not be bundled. You just need to remove the calls and imports from the hooks and the `example.ts` will be excluded.

**Comment by denismaier** [comment]
Thanks.
