### ISSUE TITLE
How to make existing plugin compatible with Zotero 7 using this template?

### ISSUE THREAD

**Issue by denismaier** [windingwind/zotero-plugin-template#79]
I'm maintaining a [small plugin](https://github.com/ub-unibe-ch/zotero-swissbib-bb-locations) used internally at our library, and I'll still need to make it compatible with Zotero 7. I thought using this template would be the easiest, and, given the multiple convenience feature it provides, also the most pleasant way. But, how would you actually do that? Clone the template into a new branch (how?), copy the relevant features, and, once Zotero 7 has been released, build a release from there? Any hints how that would be done most easily?

**Comment by windingwind** [comment]
For me, I clone the template and implement the plugin there. Once it's done, create a branch in the target git repo and replace (alternatively, wtih rebase) all files there with the files from the new implementation.

**Comment by denismaier** [comment]
Thanks. Sounds like a solid approach.
