### ISSUE TITLE
vTable for data entry?

### ISSUE THREAD

**Issue by denismaier** [windingwind/zotero-plugin-template#82]
Can I use the vtable container for manipulating settings? (E.g., I have a bunch of related settings, and I don't want to add an input box for each, but rather have them show up together in a table? Is that possible?

**Comment by windingwind** [comment]
See how the actions plugin does this: https://github.com/windingwind/zotero-actions-tags/blob/master/src/modules/preferenceWindow.ts

**Comment by windingwind** [comment]
Close for not active. Please feel free to open it again.
