### ISSUE TITLE
killZoteroUnix should ignore grep process

### ISSUE THREAD

**Issue by daeh** [windingwind/zotero-plugin-template#88]
Thank you for making this amazing template. It's a remarkable contribution. It's amazingly extensive and clear. 

A fairly minor thing, but on nix systems, the current kill command tries to kill the grep process that it calls in the pipe.

I've been using `kill -9 $(ps -x | grep '[z]otero' | awk '{print $1}')` to only capture the zotero process and ignore the grep command. Does it make sense to update `killZoteroUnix` in `zotero-cmd-template.json`?

(If it makes sense to update the command and you'd like me to open a PR for that file, let me know).

**Comment by windingwind** [comment]
thanks for pointing it out! PR is always welcome :)
