### ISSUE TITLE
How to create a development environment without affecting normal use?

### ISSUE THREAD

**Issue by ChenglongMa** [windingwind/zotero-plugin-template#96]
Hi @windingwind,

Thanks for the great template!

I am developing a plugin which works in Zotero 6 and 7. However, when I test the plugin, the settings and database of normal Zotero will be affected accordingly.

How can I create a dev env so that I can use another Zotero normally. Like:

1. Zotero 7 Normal: I will manage my own literature for paper writing.
2. Zotero 7 Dev: A separate **database**, **settings** and **profile**.
3. Zotero 6 Dev: A separate **database**, **settings** and **profile**.

Thanks!

**Comment by windingwind** [comment]
https://github.com/windingwind/zotero-plugin-template/blob/main/scripts/zotero-cmd-template.json

**Comment by windingwind** [comment]
I won't recommend supporting Z6 for a new plugin. Z6 is going to its end of support very soon.

**Comment by northword** [comment]
如果你确需要支持 Z6，可以参考先前的模板修改 `start.mjs`：

https://github.com/windingwind/zotero-plugin-template/blob/9850e5e67633a808eed138e651d4266bc304a45f/scripts/zotero-cmd-default.json#L6

https://github.com/windingwind/zotero-plugin-template/blob/9850e5e67633a808eed138e651d4266bc304a45f/scripts/start.mjs#L20

PS：我个人的意见也是放弃支持 Z6，当然这个看具体开发者意愿咯。

**Comment by ChenglongMa** [comment]
感谢二位的回复，我也正逐步暂停Z6版本的更新。

谢谢！

**Comment by YaoLiMuMu** [comment]
@northword @windingwind  我现在在用zotero6 bootstrap, 尝试开发插件, 但是使用模板build 的xpi插件不起作用, 我只改了package.json里面的name 和id, 下面是zotero 启动后打印出来的debug log, 请问下是什么原因导致的 
debug log(zotero 6):
```
[JavaScript Error: "expected expression, got '.'" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/chrome/content/scripts/index.js" line: 5877 column: 31 source: "      return addon.data.locale?.stringBundle.GetStringFromName(localString);
"}]
startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/madhouse/.zotero/zotero/9nlboxq4.default/extensions/nebula1703@nebula.com.xpi!/bootstrap.js:99:3
```
我目前想要开发的功能是可以通过pdf的注释添加引用后, 直接链接跳转到另一个pdf的注释页面(引文的页面), 网上好像没有人做这个功能, 要不就不会这么伤脑筋了.
