### ISSUE TITLE
What's the rule of the xhtml?

### ISSUE THREAD

**Issue by YtihalX** [windingwind/zotero-plugin-template#99]
What's the rule of the xhtml file, like `preferences.xhtml`?  I've looked up the MDN and  it seems to be non standard xml, and I didn't find it in the repo's document or anywhere else.

**Comment by windingwind** [comment]
https://developer.mozilla.org/en-US/docs/Glossary/XHTML

It is/can be privileged with support to XUL elements (https://docs.huihoo.com/xul/xul-element-reference/) in Zotero, compared to HTML, which is non-privileged.

**Comment by YtihalX** [comment]
So it's XUL instead of HTML?  

Well thanks, I'll pick up some XUL then.

**Comment by windingwind** [comment]
It supports both XUL and HTML elements, to be clear

**Comment by YtihalX** [comment]
Sorry I don't get it, then won't these two cause conflicts?
I mean, can `preferences.xhtml` be interpreted both as XUL and as HTML?

**Comment by windingwind** [comment]
nothing will be interpreted; `xhtml` is natively supported. and there won't be conflicts, XUL and HTML are under different namespace.

In preferences.xhtml I think it defaults to XUL and you can create HTML elements with `<html:div></html:div>`:

```
xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"
xmlns:html="http://www.w3.org/1999/xhtml"
```

**Comment by YtihalX** [comment]
gotcha, thanks for your patient explanations :+1:
